name: build-release
run-name: build-release

on:
  push:
    tags:
      - "*"

jobs:
  desktop:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create virtual environment
        run: |
          python -m venv venv

      - name: Install Qt deploy tooling
        shell: bash
        run: |
          source venv/bin/activate || .\\venv\\Scripts\\activate
          python -m pip install --upgrade pip
          pip install pyside6

      - name: Build desktop app
        shell: bash
        run: |
          source venv/bin/activate || .\\venv\\Scripts\\activate
          pyside6-deploy -c pysidedeploy.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: desktop-${{ runner.os }}
          path: dist/*
  # android:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: "3.11"

  #     - name: Install Android deploy tooling
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install pyside6 pyside6-android-deploy buildozer qtpip

  #     - name: Download PySide6 Android wheels
  #       run: |
  #         qtpip download PySide6 --android --arch aarch64
  #         qtpip download shiboken6 --android --arch aarch64

  #     - name: Build Android APK
  #       run: |
  #         pyside6-android-deploy --config-file pysidedeploy.spec --force

  #     - name: Upload Android artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: android
  #         path: "*.apk"

  release:
    # needs: [ desktop, android ]
    needs: desktop
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: dist/**
