name: build-release
run-name: build-release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          VERSION=$(cat .version)
          OS=$(echo "${{ runner.os }}" | tr '[:upper:]' '[:lower:]')
          pyinstaller gui.py \
            -n grocycode-${VERSION}-${OS} \
            -F \
            --add-data ".version:." \
            --add-data "assets:assets"

      - name: Build (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          VERSION=$(cat .version)
          pyinstaller gui.py modules/*.py \
            -n grocycode-${VERSION}-windows \
            -F \
            --add-data ".version;." \
            --add-data "assets;assets"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: grocycode-${{ runner.os }}
          path: dist/*
  release:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          generate_release_notes: true
          files: dist/**
